"""Management access for Moxa NPort device servers used by GSVpiko.

This module configures the NPort side of a GSV connection before the normal
GSV byte-stream transport is opened. It is intentionally separate from
``transport_serial`` and ``transport_tcp`` because it does not carry GSV protocol
frames. It configures the serial device server around that byte stream.

Scope
-----
``transport_nport`` prepares the Moxa NPort 5110A so that the later transport
layer can open the requested GSV byte stream. The target state is derived from
the resolved device/setup configuration:

* requested ``connection_type == "tcp"`` -> NPort ``TCP Server Mode``
* requested ``connection_type == "serial"`` -> NPort ``Real COM Mode``
* requested ``baudrate`` -> NPort serial baudrate for the NPort-to-GSV link

The module does not parse or send GSV protocol frames. It also does not create
or repair the Windows Real COM driver mapping. It only changes the NPort device
server itself.

Terminology
-----------
The terms below follow the NPort web console and should be used in user-visible
NPort output:

* ``TCP Server Mode``: GSVpiko connects directly to the NPort data socket,
  normally TCP port 4001.
* ``Real COM Mode``: the Moxa Windows driver exposes the NPort as a local COM
  port. The NPort data service was observed on TCP port 950, while the local COM
  mapping remains a Windows driver/NPort Administrator matter.

The internal GSVpiko connection type names remain short and transport-oriented:
``"tcp"`` and ``"serial"``.

Reverse-engineered management path
----------------------------------
Some NPort 5110A configurations do not expose Telnet management. In that
case, the working management path is the HTTP web console on port 80. Direct
configuration POSTs must follow the NPort login flow because the web console
binds form submissions to an authenticated session. The required sequence is:

1. GET ``/`` and read the hidden ``FakeChallenge`` value from the login form.
2. POST ``/`` with ``EncPasswd`` and ``EncUser`` computed like the login page
   JavaScript.
3. Follow the ``307`` redirect to ``/LoginOK.htm``.
4. Continue past the web-log warning page by sending the non-destructive
   ``Continue`` action to ``/action.htm``. Do not send the clear-log action.
5. GET ``/CommPara.htm?Port=1`` and submit the serial communication form to
   ``/Set.htm``.
6. GET ``/opmode.htm?Port=1`` and submit the operating-mode form to
   ``/Set.htm``.
7. GET ``/savRst.htm`` and submit the Save/Restart form to ``/Restart.htm``.
8. Poll the data port that proves the requested mode is reachable.

``FakeChallenge`` is a nonce-like login challenge generated by the NPort web
console. It binds the submitted login hash to the current login page instance.
The NPort expects the password and username fields to be transformed using this
challenge. Without this step, the server returns the login page or a
session-expired page and ignores later configuration POSTs.

Login form details used by the NPort 5110A web console:

* login page: ``/``
* form method: ``POST``
* form action: ``/``
* visible ``Username`` and ``Password`` fields are disabled by JavaScript before
  submission
* hidden/request fields: ``EncPasswd``, ``EncUser``, ``FakeChallenge``
* ``EncPasswd = SHA256(username + password + FakeChallenge)``
* ``EncUser = encodePassword(username, SHA256(FakeChallenge))``
* successful login returns ``307`` to ``/LoginOK.htm`` and sets a ``ChallID``
  cookie

The important implementation detail is ``encodePassword``: it is not simply
``SHA256(username + SHA256(FakeChallenge))``. The logic was taken from the
NPort login page JavaScript.

Pages and scripts behind the login
----------------------------------
The pages and scripts below are relevant to NPort web-console navigation. Not
all of them are used by this module, but documenting them keeps the management
path reproducible.

Navigation / frame pages:

* ``/LoginOK.htm``: post-login redirect target
* ``/action.htm``: warning/continue action endpoint
* ``/Password.htm``: page reached after the non-destructive Continue action
* ``/home.htm``
* ``/contents.htm``: menu/tree with links to configuration pages
* ``/main.htm``
* ``/top.htm``

Configuration pages:

* ``/Basic.htm``
* ``/Network.htm``
* ``/net_basic.htm``
* ``/IPTab.htm``
* ``/Serial.htm``
* ``/port.htm``
* ``/sio.htm``
* ``/line.htm``
* ``/CommPara.htm?Port=1``: serial communication parameters
* ``/opmode.htm?Port=1``: operating mode settings
* ``/operating.htm``
* ``/operating_settings.htm``
* ``/savRst.htm``: Save/Restart form
* ``/Restart.htm``: Save/Restart submit target
* ``/ChPwd.htm``
* ``/status.htm``
* ``/overview.htm``
* ``/wizard.htm``
* ``/wizard1.htm``
* ``/wizCont.htm``

JavaScript/assets observed:

* ``/nport.js``
* ``/sha256.js``
* ``/opmode.js``
* ``/valid.js``
* ``/tree.js``
* ``/wiz.js``
* ``/xss.js``

Operating mode values from ``opmode.htm``
-----------------------------------------
GSVpiko uses ``Real COM Mode`` and ``TCP Server Mode``. The remaining values
are listed because the NPort web page exposes them.

* ``OpMode=0``  -> ``Pair Connection Slave``
* ``OpMode=1``  -> ``Pair Connection Master``
* ``OpMode=2``  -> ``RealCOM`` / ``Real COM Mode``
* ``OpMode=7``  -> ``Disable``
* ``OpMode=8``  -> ``Reverse Telnet``
* ``OpMode=10`` -> ``TCP Server`` / ``TCP Server Mode``
* ``OpMode=12`` -> ``Ethernet Modem``
* ``OpMode=13`` -> ``TCP Client``
* ``OpMode=14`` -> ``UDP``
* ``OpMode=20`` -> ``RFC2217``

Additional operating-mode form fields observed:

* ``TCPAliveCheck`` default/observed value: ``7`` minutes
* ``MaxConnect`` default/observed value: ``1``
* ``IgnoreJam`` values: ``0``/``1``
* ``AllowDrvCtrl`` values: ``0``/``1``
* form action: ``Set.htm``
* hidden fields include ``Port=1``, ``setfunc="Operation Modes"`` and
  ``csrf_token``

Serial communication values discovered from ``CommPara.htm?Port=1``
-------------------------------------------------------------------
Baudrate values on ``CommPara.htm``:

* ``BaudRate=0``  -> ``50``
* ``BaudRate=1``  -> ``75``
* ``BaudRate=2``  -> ``110``
* ``BaudRate=3``  -> ``134``
* ``BaudRate=4``  -> ``150``
* ``BaudRate=5``  -> ``300``
* ``BaudRate=6``  -> ``600``
* ``BaudRate=7``  -> ``1200``
* ``BaudRate=8``  -> ``1800``
* ``BaudRate=9``  -> ``2400``
* ``BaudRate=10`` -> ``4800``
* ``BaudRate=11`` -> ``7200``
* ``BaudRate=12`` -> ``9600``
* ``BaudRate=13`` -> ``19200``
* ``BaudRate=14`` -> ``38400``
* ``BaudRate=15`` -> ``57600``
* ``BaudRate=16`` -> ``115200``
* ``BaudRate=17`` -> ``230400``
* ``BaudRate=18`` -> ``460800``
* ``BaudRate=19`` -> ``921600``

Serial parameter values observed:

* ``DataBits=0`` -> 5 data bits
* ``DataBits=1`` -> 6 data bits
* ``DataBits=2`` -> 7 data bits
* ``DataBits=3`` -> 8 data bits
* ``StopBits=0`` -> 1 stop bit
* ``StopBits=1`` -> 1.5 stop bits
* ``StopBits=2`` -> 2 stop bits
* ``Parity=0``  -> None
* ``Parity=8``  -> Odd
* ``Parity=24`` -> Even
* ``Parity=40`` -> Mark
* ``Parity=56`` -> Space
* ``FlowCtrl=0`` -> None
* ``FlowCtrl=1`` -> RTS/CTS, observed in earlier web-form reads
* ``FlowCtrl=2`` -> XON/XOFF
* ``FlowCtrl=3`` -> DTR/DSR
* ``FIFODisable=1`` -> FIFO enabled in the web form wording
* ``FIFODisable=0`` -> FIFO disabled in the web form wording
* ``IfType=0`` -> RS-232 on the NPort 5110A page
* form action: ``Set.htm``
* hidden fields include ``Port=1``, ``setfunc="Communication Parameters"`` and
  ``csrf_token``

Save/Restart form discovered from ``savRst.htm``
------------------------------------------------
Changing forms is not enough. The NPort requires Save/Restart before the new
configuration is applied.

* form name: ``savRst``
* form action: ``Restart.htm``
* hidden ``setfunc=SaveRestart``
* hidden ``csrf_token``

Port-based state detection
--------------------------
The module uses data-port reachability as a practical post-condition check:

* ``TCP Server Mode`` is considered reachable when TCP port 4001 opens.
* ``Real COM Mode`` is considered reachable when the Real COM data service
  around TCP port 950 opens.

Known management/service ports:

* ``23``: Telnet management, not reachable on the tested devices
* ``80``: HTTP web console, working management path
* ``950``: Real COM data service used as mode indicator
* ``966``: NPort command/control service, not the GSV byte stream
* ``4001``: raw TCP Server Mode data port used for GSVpiko TCP transport
* ``4900``: Moxa service/firmware-related port
* ``4800/UDP``: Moxa discovery/settings-related port

The module keeps unmodified form fields from the NPort pages whenever possible.
Only fields that must change for the requested setup are overwritten.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import html
import http.client
import re
import socket
import time
import urllib.parse
from typing import Any, Iterable


NPORT_MODE_TCP_SERVER = "tcp_server"
NPORT_MODE_REALCOM = "realcom"
NPORT_MODE_UNKNOWN = "unknown"
NPORT_MODE_AMBIGUOUS = "ambiguous"

NPORT_MODE_NAME_BY_MODE = {
    NPORT_MODE_TCP_SERVER: "TCP Server Mode",
    NPORT_MODE_REALCOM: "Real COM Mode",
    NPORT_MODE_UNKNOWN: "unknown",
    NPORT_MODE_AMBIGUOUS: "ambiguous",
}

# Full operating-mode table observed on opmode.htm. GSVpiko uses Real COM Mode
# and TCP Server Mode. The remaining entries are kept with the form mapping so
# NPort handling can be extended without rediscovering web-form values.
NPORT_WEB_OPMODE_NAME_BY_VALUE = {
    "0": "Pair Connection Slave",
    "1": "Pair Connection Master",
    "2": "Real COM Mode",
    "7": "Disable",
    "8": "Reverse Telnet",
    "10": "TCP Server Mode",
    "12": "Ethernet Modem",
    "13": "TCP Client",
    "14": "UDP",
    "20": "RFC2217",
}

NPORT_WEB_OPMODE_VALUE_BY_NAME = {
    name: value for value, name in NPORT_WEB_OPMODE_NAME_BY_VALUE.items()
}

NPORT_DISCOVERED_WEB_PAGES = (
    "/",
    "/LoginOK.htm",
    "/action.htm",
    "/Password.htm",
    "/home.htm",
    "/contents.htm",
    "/main.htm",
    "/top.htm",
    "/Basic.htm",
    "/Network.htm",
    "/net_basic.htm",
    "/IPTab.htm",
    "/Serial.htm",
    "/port.htm",
    "/sio.htm",
    "/line.htm",
    "/CommPara.htm?Port=1",
    "/opmode.htm?Port=1",
    "/operating.htm",
    "/operating_settings.htm",
    "/savRst.htm",
    "/Restart.htm",
    "/ChPwd.htm",
    "/status.htm",
    "/overview.htm",
    "/wizard.htm",
    "/wizard1.htm",
    "/wizCont.htm",
)

NPORT_DISCOVERED_SCRIPT_FILES = (
    "/nport.js",
    "/sha256.js",
    "/opmode.js",
    "/valid.js",
    "/tree.js",
    "/wiz.js",
    "/xss.js",
)

NPORT_SERIAL_DATABITS_BY_WEB_VALUE = {
    "0": 5,
    "1": 6,
    "2": 7,
    "3": 8,
}

NPORT_SERIAL_STOPBITS_BY_WEB_VALUE = {
    "0": "1",
    "1": "1.5",
    "2": "2",
}

NPORT_SERIAL_PARITY_BY_WEB_VALUE = {
    "0": "None",
    "8": "Odd",
    "24": "Even",
    "40": "Mark",
    "56": "Space",
}

NPORT_SERIAL_FLOW_CONTROL_BY_WEB_VALUE = {
    "0": "None",
    "1": "RTS/CTS",
    "2": "XON/XOFF",
    "3": "DTR/DSR",
}

# Target serial-line values used by the GSV-8/NPort-5110A path. Flow control is
# deliberately disabled because an unverified RTS/CTS hardware-handshake path can
# make the NPort data port reachable while serial bytes are not forwarded
# reliably.
NPORT_TARGET_SERIAL_FIELD_VALUES = {
    "DataBits": "3",      # 8 data bits
    "StopBits": "0",      # 1 stop bit
    "Parity": "0",        # None
    "FlowCtrl": "0",      # None
    "IfType": "0",        # RS-232 on the NPort 5110A web page
    "FIFODisable": "1",   # FIFO enabled in the observed web-form wording
}

NPORT_MODE_FOR_CONNECTION_TYPE = {
    "tcp": NPORT_MODE_TCP_SERVER,
    "serial": NPORT_MODE_REALCOM,
}

NPORT_WEB_OPMODE_VALUE_BY_MODE = {
    NPORT_MODE_REALCOM: "2",
    NPORT_MODE_TCP_SERVER: "10",
}

NPORT_BAUDRATE_WEB_VALUE_BY_RATE = {
    50: "0",
    75: "1",
    110: "2",
    134: "3",
    150: "4",
    300: "5",
    600: "6",
    1200: "7",
    1800: "8",
    2400: "9",
    4800: "10",
    7200: "11",
    9600: "12",
    19200: "13",
    38400: "14",
    57600: "15",
    115200: "16",
    230400: "17",
    460800: "18",
    921600: "19",
}

NPORT_RATE_BY_BAUDRATE_WEB_VALUE = {
    value: rate for rate, value in NPORT_BAUDRATE_WEB_VALUE_BY_RATE.items()
}

DEFAULT_NPORT_USERNAME = "admin"
DEFAULT_NPORT_PASSWORD = "moxa"
DEFAULT_NPORT_HTTP_PORT = 80
DEFAULT_NPORT_COMMAND_PORT = 966
DEFAULT_NPORT_TELNET_PORT = 23
DEFAULT_NPORT_TCP_DATA_PORT = 4001
DEFAULT_NPORT_REALCOM_DATA_PORT = 950
DEFAULT_NPORT_CONNECT_TIMEOUT_S = 3.0
DEFAULT_NPORT_READ_TIMEOUT_S = 4.0
DEFAULT_NPORT_APPLY_SETTLE_TIMEOUT_S = 25.0
DEFAULT_NPORT_APPLY_POLL_INTERVAL_S = 0.75
DEFAULT_NPORT_POST_RESTART_EXTRA_SETTLE_S = 0.5
DEFAULT_NPORT_TCP_ALIVE_CHECK_MIN = 7
DEFAULT_NPORT_MAX_CONNECTIONS = 1


class NportConfigurationError(RuntimeError):
    """Raised when NPort management fails before a requested configuration."""


@dataclass(frozen=True)
class NportTargetSettings:
    """Requested NPort settings derived from a resolved device config."""

    ip_address: str
    mode: str
    baudrate: int
    tcp_port: int = DEFAULT_NPORT_TCP_DATA_PORT
    command_port: int = DEFAULT_NPORT_COMMAND_PORT
    realcom_data_port: int = DEFAULT_NPORT_REALCOM_DATA_PORT
    username: str = DEFAULT_NPORT_USERNAME
    password: str = DEFAULT_NPORT_PASSWORD
    http_port: int = DEFAULT_NPORT_HTTP_PORT
    telnet_port: int = DEFAULT_NPORT_TELNET_PORT
    timeout_s: float = DEFAULT_NPORT_CONNECT_TIMEOUT_S
    read_timeout_s: float = DEFAULT_NPORT_READ_TIMEOUT_S
    settle_timeout_s: float = DEFAULT_NPORT_APPLY_SETTLE_TIMEOUT_S
    port_number: int = 1
    tcp_alive_check_min: int = DEFAULT_NPORT_TCP_ALIVE_CHECK_MIN
    max_connections: int = DEFAULT_NPORT_MAX_CONNECTIONS
    post_restart_extra_settle_s: float = DEFAULT_NPORT_POST_RESTART_EXTRA_SETTLE_S


@dataclass
class NportApplyReport:
    """Result of one optional NPort management attempt."""

    requested: bool
    attempted: bool
    ok: bool
    mode: str | None = None
    ip_address: str | None = None
    baudrate: int | None = None
    tcp_port: int | None = None
    command_port: int | None = None
    message: str | None = None
    error: str | None = None
    transcript_tail: str | None = None
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Return a plain dictionary representation."""
        return {
            "requested": self.requested,
            "attempted": self.attempted,
            "ok": self.ok,
            "mode": self.mode,
            "mode_name": format_nport_mode(self.mode),
            "ip_address": self.ip_address,
            "baudrate": self.baudrate,
            "tcp_port": self.tcp_port,
            "command_port": self.command_port,
            "message": self.message,
            "error": self.error,
            "transcript_tail": self.transcript_tail,
            "warnings": list(self.warnings),
        }


def format_nport_mode(mode: str | None) -> str | None:
    """Return the NPort web-console name for an internal NPort mode value."""
    if mode is None:
        return None
    return NPORT_MODE_NAME_BY_MODE.get(mode, str(mode))


def desired_nport_mode_for_connection_type(connection_type: str) -> str:
    """Return the NPort operating mode needed for one GSVpiko connection type."""
    try:
        return NPORT_MODE_FOR_CONNECTION_TYPE[connection_type]
    except KeyError as error:
        raise ValueError(
            f"Unsupported connection_type for NPort management: {connection_type!r}."
        ) from error


def build_nport_target_from_device_config(
    device_config: dict[str, Any],
) -> NportTargetSettings | None:
    """Build requested NPort settings from a resolved device config.

    Returns None when the device is not configured to use an NPort.
    """
    if not bool(device_config.get("default_use_nport", False)):
        return None

    ip_address = device_config.get("ip_address")
    if not ip_address:
        raise NportConfigurationError(
            f"Device {device_config.get('name', '<unnamed>')!r} uses an NPort but has no ip_address."
        )

    connection_type = str(device_config.get("default_connection_type", "serial"))
    return NportTargetSettings(
        ip_address=str(ip_address),
        mode=desired_nport_mode_for_connection_type(connection_type),
        baudrate=int(device_config["default_baudrate"]),
        tcp_port=int(device_config.get("tcp_port", DEFAULT_NPORT_TCP_DATA_PORT)),
        command_port=int(device_config.get("nport_command_port", DEFAULT_NPORT_COMMAND_PORT)),
        realcom_data_port=int(
            device_config.get("nport_realcom_data_port", DEFAULT_NPORT_REALCOM_DATA_PORT)
        ),
        username=str(device_config.get("default_nport_username") or DEFAULT_NPORT_USERNAME),
        password=str(device_config.get("default_nport_password") or DEFAULT_NPORT_PASSWORD),
        http_port=int(device_config.get("nport_http_port", DEFAULT_NPORT_HTTP_PORT)),
        telnet_port=int(device_config.get("nport_telnet_port", DEFAULT_NPORT_TELNET_PORT)),
        timeout_s=float(device_config.get("nport_timeout_s", DEFAULT_NPORT_CONNECT_TIMEOUT_S)),
        read_timeout_s=float(device_config.get("nport_read_timeout_s", DEFAULT_NPORT_READ_TIMEOUT_S)),
        settle_timeout_s=float(
            device_config.get("nport_settle_timeout_s", DEFAULT_NPORT_APPLY_SETTLE_TIMEOUT_S)
        ),
        port_number=int(device_config.get("nport_port_number", 1)),
        tcp_alive_check_min=int(
            device_config.get("nport_tcp_alive_check_min", DEFAULT_NPORT_TCP_ALIVE_CHECK_MIN)
        ),
        max_connections=int(
            device_config.get("nport_max_connections", DEFAULT_NPORT_MAX_CONNECTIONS)
        ),
        post_restart_extra_settle_s=float(
            device_config.get(
                "nport_post_restart_extra_settle_s",
                DEFAULT_NPORT_POST_RESTART_EXTRA_SETTLE_S,
            )
        ),
    )


def apply_nport_settings_from_device_config(
    device_config: dict[str, Any],
) -> NportApplyReport:
    """Apply requested NPort settings when the device config asks for it.

    This function prepares the NPort so that the requested GSVpiko transport can
    open the data path afterwards. It uses the tested web-form path and returns
    a detailed report instead of hiding management failures.
    """
    if not bool(device_config.get("default_use_nport", False)):
        return NportApplyReport(
            requested=False,
            attempted=False,
            ok=True,
            message="Device is not configured to use an NPort.",
        )

    if not bool(device_config.get("default_configure_nport", False)):
        return NportApplyReport(
            requested=False,
            attempted=False,
            ok=True,
            message="NPort management is disabled for this device config.",
        )

    target = build_nport_target_from_device_config(device_config)
    if target is None:
        return NportApplyReport(
            requested=False,
            attempted=False,
            ok=True,
            message="No NPort target settings are required.",
        )

    return _apply_nport_settings_via_web(target)


def detect_nport_data_mode(target: NportTargetSettings) -> tuple[str, str]:
    """Detect the reachable NPort data mode using the known data ports."""
    tcp_open = _tcp_port_is_open(
        target.ip_address,
        target.tcp_port,
        timeout_s=min(target.timeout_s, 0.7),
    )
    realcom_open = _tcp_port_is_open(
        target.ip_address,
        target.realcom_data_port,
        timeout_s=min(target.timeout_s, 0.7),
    )

    if tcp_open and not realcom_open:
        return NPORT_MODE_TCP_SERVER, f"TCP Server data port {target.tcp_port} is open."
    if realcom_open and not tcp_open:
        return NPORT_MODE_REALCOM, f"Real COM data port {target.realcom_data_port} is open."
    if tcp_open and realcom_open:
        return NPORT_MODE_AMBIGUOUS, (
            f"Both TCP Server data port {target.tcp_port} and Real COM data port "
            f"{target.realcom_data_port} are open."
        )
    return NPORT_MODE_UNKNOWN, (
        f"Neither TCP Server data port {target.tcp_port} nor Real COM data port "
        f"{target.realcom_data_port} is open."
    )


def _tcp_port_is_open(
    host: str,
    port: int,
    *,
    timeout_s: float,
) -> bool:
    """Return whether a TCP port can be opened quickly."""
    try:
        with socket.create_connection((host, int(port)), timeout=timeout_s):
            return True
    except OSError:
        return False


class _NportWebSession:
    """Small HTTP session for the NPort web console."""

    def __init__(self, target: NportTargetSettings) -> None:
        self.target = target
        self.cookies: dict[str, str] = {}
        self.log: list[str] = []

    def _cookie_header(self) -> str:
        return "; ".join(f"{name}={value}" for name, value in sorted(self.cookies.items()))

    def _store_set_cookie(self, headers: Iterable[tuple[str, str]]) -> None:
        for name, value in headers:
            if name.lower() != "set-cookie":
                continue
            first = value.split(";", 1)[0]
            if "=" in first:
                cookie_name, cookie_value = first.split("=", 1)
                self.cookies[cookie_name.strip()] = cookie_value.strip()

    def request(
        self,
        method: str,
        path: str,
        *,
        body: bytes | None = None,
        headers: dict[str, str] | None = None,
        log_name: str,
    ) -> tuple[int, str, list[tuple[str, str]], str]:
        """Send one HTTP request and return decoded response text."""
        if not path.startswith("/"):
            path = "/" + path

        request_headers = {
            "Host": self.target.ip_address,
            "User-Agent": "GSVpiko-NPort-Web-Configurator",
            "Connection": "close",
        }
        if self.cookies:
            request_headers["Cookie"] = self._cookie_header()
        if headers:
            request_headers.update(headers)

        connection = http.client.HTTPConnection(
            self.target.ip_address,
            self.target.http_port,
            timeout=self.target.read_timeout_s,
        )
        try:
            connection.request(method.upper(), path, body=body, headers=request_headers)
            response = connection.getresponse()
            data = response.read()
            response_headers = response.getheaders()
            self._store_set_cookie(response_headers)
            text = data.decode("utf-8", errors="replace")
            self.log.append(
                f"{log_name}: {method.upper()} {path} -> {response.status} {response.reason}; "
                f"bytes={len(data)}; title={_extract_title(text)!r}"
            )
            return response.status, response.reason, response_headers, text
        finally:
            connection.close()

    def get(self, path: str, *, log_name: str) -> tuple[int, str, list[tuple[str, str]], str]:
        """Send one HTTP GET request."""
        return self.request("GET", path, log_name=log_name)

    def get_with_query(
        self,
        path: str,
        params: dict[str, str],
        *,
        log_name: str,
    ) -> tuple[int, str, list[tuple[str, str]], str]:
        """Send one HTTP GET request with query parameters."""
        query = urllib.parse.urlencode(params)
        return self.get(f"{path}?{query}", log_name=log_name)


def _apply_nport_settings_via_web(target: NportTargetSettings) -> NportApplyReport:
    """Apply NPort settings through the tested web-console forms."""
    session = _NportWebSession(target)
    warnings: list[str] = []

    before_mode, before_detail = detect_nport_data_mode(target)
    session.log.append(f"before: {format_nport_mode(before_mode)} ({before_detail})")

    try:
        login_ok, login_message = _login_web_console(session)
        session.log.append(f"web_login_ok={login_ok}; {login_message}")
        if not login_ok:
            return _web_report(
                target,
                ok=False,
                message="NPort web login failed.",
                error=login_message,
                session=session,
                warnings=warnings,
            )

        baudrate_changed = _ensure_web_baudrate(session, target)
        opmode_changed = _ensure_web_operating_mode(session, target)

        if not baudrate_changed and not opmode_changed:
            after_mode, after_detail = detect_nport_data_mode(target)
            session.log.append(f"after: {format_nport_mode(after_mode)} ({after_detail})")
            ok = after_mode == target.mode
            return _web_report(
                target,
                ok=ok,
                message=(
                    "NPort web console already matched the requested operating mode and baudrate."
                    if ok
                    else "NPort web forms matched, but the requested data path is not reachable."
                ),
                error=None if ok else after_detail,
                session=session,
                warnings=warnings,
            )

        restart_ok = _save_and_restart_web_console(session)
        if not restart_ok:
            return _web_report(
                target,
                ok=False,
                message="NPort web settings were submitted, but Save/Restart failed.",
                error="Save/Restart form could not be submitted successfully.",
                session=session,
                warnings=warnings,
            )

        ready, ready_detail = _wait_until_target_reachable(target)
        if ready and target.post_restart_extra_settle_s > 0:
            session.log.append(
                "post_restart_extra_settle: "
                f"waiting {target.post_restart_extra_settle_s:.1f} s before final data-port check"
            )
            time.sleep(target.post_restart_extra_settle_s)
            final_ready, final_detail = _wait_until_target_reachable(target)
        else:
            final_ready, final_detail = ready, ready_detail

        after_mode, after_detail = detect_nport_data_mode(target)
        session.log.append(f"after: {format_nport_mode(after_mode)} ({after_detail})")
        ok = final_ready and after_mode == target.mode
        if not final_ready:
            warnings.append(final_detail)
        elif after_mode != target.mode:
            warnings.append(
                "Final NPort data-port check did not match the requested mode after the "
                f"extra settle interval: {after_detail}"
            )

        return _web_report(
            target,
            ok=ok,
            message=(
                f"NPort was configured through the web console and reached "
                f"{format_nport_mode(target.mode)}."
                if ok
                else "NPort web settings were submitted, but final target reachability was not confirmed."
            ),
            error=None if ok else final_detail,
            session=session,
            warnings=warnings,
        )
    except Exception as error:
        return _web_report(
            target,
            ok=False,
            message="NPort web configuration failed.",
            error=str(error),
            session=session,
            warnings=warnings,
        )


def _web_report(
    target: NportTargetSettings,
    *,
    ok: bool,
    message: str,
    error: str | None,
    session: _NportWebSession,
    warnings: list[str],
) -> NportApplyReport:
    """Build a report for one web-management attempt."""
    return NportApplyReport(
        requested=True,
        attempted=True,
        ok=ok,
        mode=target.mode,
        ip_address=target.ip_address,
        baudrate=target.baudrate,
        tcp_port=target.tcp_port,
        command_port=target.command_port,
        message=message,
        error=error,
        transcript_tail="\n".join(session.log[-24:]),
        warnings=warnings,
    )


def _login_web_console(session: _NportWebSession) -> tuple[bool, str]:
    """Log into the NPort web console using the page's challenge algorithm."""
    status, reason, _headers, body = session.get("/", log_name="login_page")
    if status != 200:
        return False, f"Login page status was {status} {reason}."

    challenge = _find_input_value(body, "FakeChallenge")
    if not challenge:
        return False, "FakeChallenge was not found in the login page."
    if len(challenge) < 32:
        return False, f"FakeChallenge looked invalid: {challenge!r}."

    enc_passwd = _sha256_hex(session.target.username + session.target.password + challenge)
    enc_user = _encode_password_like_nport_js(session.target.username, _sha256_hex(challenge))
    payload = {
        "Username": session.target.username,
        "Password": "",
        "EncPasswd": enc_passwd,
        "EncUser": enc_user,
        "FakeChallenge": challenge,
    }
    body_bytes = urllib.parse.urlencode(payload).encode("ascii")
    status, reason, headers, response_text = session.request(
        "POST",
        "/",
        body=body_bytes,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        log_name="post_login",
    )

    location = _get_header(headers, "Location")
    if status in {301, 302, 303, 307, 308} and location:
        redirect_path = urllib.parse.urlparse(location).path or "/"
        status2, reason2, _headers2, body2 = session.get(
            redirect_path,
            log_name=f"redirect_{redirect_path.lstrip('/') or 'root'}",
        )
        if status2 != 200:
            return False, f"Login redirect returned {status2} {reason2}."
        if "clearWebLogAction" in body2:
            return _continue_after_web_login(session, body2)
        if _contains_login_form(body2) or "Session Expired" in body2:
            return False, "Login redirect returned a login/session-expired page."
        return True, f"Login redirected to {location}."

    if "clearWebLogAction" in response_text:
        return _continue_after_web_login(session, response_text)
    if _contains_login_form(response_text) or "Session Expired" in response_text:
        return False, f"Login was not accepted. status={status} title={_extract_title(response_text)!r}."
    return True, f"Login accepted without redirect. status={status} {reason}."


def _continue_after_web_login(
    session: _NportWebSession,
    body: str,
) -> tuple[bool, str]:
    """Continue past the web-log warning page without clearing the log."""
    csrf_token = _find_input_value(body, "csrf_token")
    if not csrf_token:
        return False, "Login reached the web-log page, but csrf_token was not found."

    params = {
        "continue": "Continue",
        "setfunc": "clearWebLogAction",
        "csrf_token": csrf_token,
    }
    status, reason, headers, response_text = session.get_with_query(
        "/action.htm",
        params,
        log_name="continue_action",
    )
    location = _get_header(headers, "Location")
    if status in {301, 302, 303, 307, 308} and location:
        redirect_path = urllib.parse.urlparse(location).path or "/"
        status2, reason2, _headers2, body2 = session.get(
            redirect_path,
            log_name=f"continue_redirect_{redirect_path.lstrip('/') or 'root'}",
        )
        if status2 != 200:
            return False, f"Continue redirect returned {status2} {reason2}."
        if _contains_login_form(body2) or "Session Expired" in body2:
            return False, "Continue redirect returned a login/session-expired page."
        return True, f"Continue accepted; redirected to {location}."

    if _contains_login_form(response_text) or "Session Expired" in response_text:
        return False, "Continue action returned a login/session-expired page."
    return True, "Continue accepted without redirect."


def _ensure_web_baudrate(session: _NportWebSession, target: NportTargetSettings) -> bool:
    """Ensure the NPort serial baudrate matches the requested setup."""
    if target.baudrate not in NPORT_BAUDRATE_WEB_VALUE_BY_RATE:
        raise NportConfigurationError(
            f"Baudrate {target.baudrate} is not represented in the discovered NPort web table."
        )

    status, reason, _headers, body = session.get(
        f"/CommPara.htm?Port={target.port_number}",
        log_name="commpara_before",
    )
    if status != 200 or _contains_login_form(body):
        raise NportConfigurationError(
            f"Serial communication settings page could not be loaded: {status} {reason}."
        )

    action, fields = _first_form_fields(body, "serial")
    requested_value = NPORT_BAUDRATE_WEB_VALUE_BY_RATE[target.baudrate]
    current_value = fields.get("BaudRate")
    current_rate = NPORT_RATE_BY_BAUDRATE_WEB_VALUE.get(str(current_value), current_value)
    session.log.append(
        f"commpara: current BaudRate={current_value} ({current_rate}); "
        f"requested BaudRate={requested_value} ({target.baudrate})"
    )

    requested_fields = dict(NPORT_TARGET_SERIAL_FIELD_VALUES)
    requested_fields["BaudRate"] = requested_value

    changed_fields: dict[str, tuple[str | None, str]] = {}
    for key, requested_field_value in requested_fields.items():
        if key not in fields:
            continue
        current_field_value = fields.get(key)
        if str(current_field_value) != requested_field_value:
            changed_fields[key] = (current_field_value, requested_field_value)
            fields[key] = requested_field_value

    if not changed_fields:
        return False

    changed_text = ", ".join(
        f"{key}: {before}->{after}"
        for key, (before, after) in sorted(changed_fields.items())
    )
    session.log.append(f"commpara_changes: {changed_text}")

    status2, reason2, _headers2, _body2 = _submit_get_form(
        session,
        action,
        fields,
        log_name="commpara_set_response",
    )
    if status2 not in {200, 301, 302, 303, 307, 308}:
        raise NportConfigurationError(
            f"Serial communication settings submit failed: {status2} {reason2}."
        )
    return True


def _ensure_web_operating_mode(session: _NportWebSession, target: NportTargetSettings) -> bool:
    """Ensure the NPort operating mode matches the requested setup."""
    if target.mode not in NPORT_WEB_OPMODE_VALUE_BY_MODE:
        raise NportConfigurationError(f"Unsupported target NPort mode {target.mode!r}.")

    requested_value = NPORT_WEB_OPMODE_VALUE_BY_MODE[target.mode]
    status, reason, _headers, body = session.get(
        f"/opmode.htm?Port={target.port_number}",
        log_name="opmode_before",
    )
    if status != 200 or _contains_login_form(body):
        raise NportConfigurationError(
            f"Operating mode page could not be loaded: {status} {reason}."
        )

    _action, current_fields = _first_form_fields(body, "opmode")
    current_value = current_fields.get("OpMode")
    session.log.append(
        f"opmode: current OpMode={current_value}; requested OpMode={requested_value} "
        f"({format_nport_mode(target.mode)})"
    )

    if str(current_value) == requested_value:
        return False

    action, fields = _load_target_opmode_form(session, target, requested_value)
    fields["OpMode"] = requested_value
    _apply_common_operating_mode_overrides(fields, target)
    status2, reason2, _headers2, _body2 = _submit_get_form(
        session,
        action,
        fields,
        log_name=f"opmode_set_{target.mode}_response",
    )
    if status2 not in {200, 301, 302, 303, 307, 308}:
        raise NportConfigurationError(
            f"Operating mode submit failed: {status2} {reason2}."
        )
    return True


def _load_target_opmode_form(
    session: _NportWebSession,
    target: NportTargetSettings,
    requested_value: str,
) -> tuple[str, dict[str, str]]:
    """Load the target-mode-specific NPort operating-mode form."""
    status, reason, _headers, body = session.get_with_query(
        "/opmode.htm",
        {"Port": str(target.port_number), "OpMode": requested_value},
        log_name=f"opmode_target_{target.mode}_form",
    )
    if status != 200 or _contains_login_form(body):
        raise NportConfigurationError(
            f"Target operating mode form could not be loaded: {status} {reason}."
        )
    return _first_form_fields(body, "opmode")


def _apply_common_operating_mode_overrides(
    fields: dict[str, str],
    target: NportTargetSettings,
) -> None:
    """Set known NPort opmode fields only when the target form exposes them."""
    if "TCPAliveCheck" in fields:
        fields["TCPAliveCheck"] = str(target.tcp_alive_check_min)
    if "MaxConnect" in fields:
        fields["MaxConnect"] = str(target.max_connections)

    port_overrides = {
        "LocalTCPPort": str(target.tcp_port),
        "LocalTcpPort": str(target.tcp_port),
        "LocalPort": str(target.tcp_port),
        "TCPPort": str(target.tcp_port),
        "TcpPort": str(target.tcp_port),
        "DataPort": str(target.tcp_port),
        "TCPServerPort": str(target.tcp_port),
        "CommandPort": str(target.command_port),
        "CmdPort": str(target.command_port),
        "TCPCommandPort": str(target.command_port),
        "ControlPort": str(target.command_port),
    }
    for key, value in port_overrides.items():
        if key in fields:
            fields[key] = value


def _save_and_restart_web_console(session: _NportWebSession) -> bool:
    """Submit the NPort Save/Restart form."""
    status, reason, _headers, body = session.get("/savRst.htm", log_name="save_restart_page")
    if status != 200 or _contains_login_form(body):
        raise NportConfigurationError(f"Save/Restart page could not be loaded: {status} {reason}.")

    action, fields = _first_form_fields(body, "savRst")
    status2, reason2, _headers2, _body2 = _submit_get_form(
        session,
        action,
        fields,
        log_name="save_restart_response",
    )
    if status2 not in {200, 301, 302, 303, 307, 308}:
        raise NportConfigurationError(f"Save/Restart submit failed: {status2} {reason2}.")
    return True


def _wait_until_target_reachable(
    target: NportTargetSettings,
) -> tuple[bool, str]:
    """Wait until the requested NPort data mode is reachable after Save/Restart."""
    deadline = time.monotonic() + max(target.settle_timeout_s, 0.0)
    last_mode = NPORT_MODE_UNKNOWN
    last_detail = ""
    while time.monotonic() < deadline:
        last_mode, last_detail = detect_nport_data_mode(target)
        if last_mode == target.mode:
            return True, last_detail
        time.sleep(DEFAULT_NPORT_APPLY_POLL_INTERVAL_S)
    return (
        False,
        f"Timed out waiting for {format_nport_mode(target.mode)}. "
        f"Last detected mode: {format_nport_mode(last_mode)}. {last_detail}",
    )


def _submit_get_form(
    session: _NportWebSession,
    action: str,
    fields: dict[str, str],
    *,
    log_name: str,
) -> tuple[int, str, list[tuple[str, str]], str]:
    """Submit a NPort form using the GET method used by the web console."""
    path = action if action.startswith("/") else "/" + action
    return session.get_with_query(path, fields, log_name=log_name)


def _first_form_fields(
    body: str,
    form_name: str | None = None,
) -> tuple[str, dict[str, str]]:
    """Return the first matching form action and field dictionary."""
    form_pattern = re.compile(r"<form\b[^>]*>.*?</form>", flags=re.IGNORECASE | re.DOTALL)
    for form_match in form_pattern.finditer(body):
        form_html = form_match.group(0)
        open_tag_match = re.search(r"<form\b[^>]*>", form_html, flags=re.IGNORECASE)
        if not open_tag_match:
            continue
        open_attrs = _attr_map(open_tag_match.group(0))
        if form_name and open_attrs.get("name") != form_name:
            continue
        action = open_attrs.get("action", "Set.htm")
        return action, _parse_form_fields(form_html)
    raise NportConfigurationError(f"Form {form_name or '<first>'!r} was not found.")


def _parse_form_fields(form_html: str) -> dict[str, str]:
    """Parse the NPort HTML form fields that must be preserved on submit."""
    fields: dict[str, str] = {}

    for match in re.finditer(
        r"inputText(?:Ex)?\(\s*\"([^\"]+)\"\s*,\s*[^,]+,\s*\"([^\"]*)\"",
        form_html,
        flags=re.IGNORECASE,
    ):
        fields.setdefault(match.group(1), html.unescape(match.group(2)))

    for match in re.finditer(r"<input\b[^>]*>", form_html, flags=re.IGNORECASE):
        attrs = _attr_map(match.group(0))
        name = attrs.get("name")
        if not name:
            continue
        input_type = attrs.get("type", "text").lower()
        if input_type in {"submit", "button", "reset"}:
            continue
        if input_type in {"checkbox", "radio"}:
            if "checked" not in {key.lower() for key in attrs}:
                continue
        fields[name] = attrs.get("value", "")

    for match in re.finditer(
        r"<select\b([^>]*)>(.*?)</select>",
        form_html,
        flags=re.IGNORECASE | re.DOTALL,
    ):
        select_attrs = _attr_map("<select " + match.group(1) + ">")
        name = select_attrs.get("name")
        if not name:
            continue
        selected_value = None
        first_value = None
        for opt_match in re.finditer(r"<option\b[^>]*>", match.group(2), flags=re.IGNORECASE):
            opt_attrs = _attr_map(opt_match.group(0))
            value = opt_attrs.get("value", "")
            if first_value is None:
                first_value = value
            if "selected" in {key.lower() for key in opt_attrs}:
                selected_value = value
                break
        fields[name] = selected_value if selected_value is not None else (first_value or "")

    return fields


def _attr_map(tag: str) -> dict[str, str]:
    """Return an attribute dictionary for a single HTML tag."""
    attrs: dict[str, str] = {}
    for match in re.finditer(
        r"([A-Za-z_][A-Za-z0-9_:-]*)"
        r"(?:\s*=\s*(?:\"([^\"]*)\"|'([^']*)'|([^\s>]+)))?",
        tag,
    ):
        key = match.group(1)
        if key.lower() in {"input", "select", "option", "form", "textarea"}:
            continue
        value = match.group(2)
        if value is None:
            value = match.group(3)
        if value is None:
            value = match.group(4)
        if value is None:
            value = ""
        attrs[key] = html.unescape(value)
    return attrs


def _find_input_value(body: str, name: str) -> str | None:
    """Find an input field value, including unquoted NPort HTML attributes."""
    for match in re.finditer(r"<input\b[^>]*>", body, flags=re.IGNORECASE):
        attrs = _attr_map(match.group(0))
        if attrs.get("name") == name:
            return attrs.get("value", "")
    return None


def _contains_login_form(body: str) -> bool:
    """Return whether an HTTP body still shows the NPort login form."""
    return "InputPassword" in body or "EncPasswd" in body or "FakeChallenge" in body


def _extract_title(body: str) -> str:
    """Return the HTML title text if present."""
    match = re.search(r"<title[^>]*>(.*?)</title>", body, flags=re.IGNORECASE | re.DOTALL)
    if not match:
        return ""
    text = re.sub(r"<[^>]+>", " ", match.group(1))
    return html.unescape(re.sub(r"\s+", " ", text).strip())


def _get_header(headers: Iterable[tuple[str, str]], key: str) -> str | None:
    """Return one HTTP header value by case-insensitive name."""
    key_lower = key.lower()
    for name, value in headers:
        if name.lower() == key_lower:
            return value
    return None


def _sha256_hex(value: str) -> str:
    """Return SHA-256 hex digest for one UTF-8 string."""
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _encode_password_like_nport_js(password: str, key: str) -> str:
    """Replicate the NPort login page's encodePassword(password, key)."""
    ascii_table = (
        "01234567890123456789012345678901"
        " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
    )
    md_values: list[int] = []
    for index in range(0, len(key), 2):
        md_values.append(int(key[index:index + 2], 16))

    result = list(md_values)
    for index, char in enumerate(password):
        char_index = ascii_table.rfind(char)
        if char_index < 0:
            raise NportConfigurationError(
                f"Character {char!r} cannot be encoded by the NPort login function."
            )
        result[index] = md_values[index] ^ char_index

    return "".join(f"{value & 0xFF:02x}" for value in result)
