"""Command number constants for the GSV protocol.

Max Piko layout.
"""

# General and setup
RESET_STATUS = 0x00
GET_INTERFACE = 0x01
READ_ZERO = 0x02
WRITE_ZERO = 0x03
READ_AOUT_OFFSET = 0x04
WRITE_AOUT_OFFSET = 0x05
READ_AOUT_SCALE = 0x06
WRITE_AOUT_SCALE = 0x07
WRITE_AOUT_DIRECT = 0x08
LOAD_CONFIG = 0x09
STORE_CONFIG = 0x0A
SET_ZERO = 0x0C
GET_AOUT_TYPE = 0x0D
SET_AOUT_TYPE = 0x0E
GET_UNIT_NO = 0x0F
SET_UNIT_NO = 0x10
GET_UNIT_TEXT = 0x11
SET_UNIT_TEXT = 0x12

# Scaling, calibration, and identification
READ_USER_SCALE = 0x14
WRITE_USER_SCALE = 0x15
READ_CAL = 0x17
WRITE_CAL = 0x18
SET_ID = 0x19
GET_ID_STATE = 0x1A
READ_SENSOR_MODEL = 0x1B
WRITE_SENSOR_MODEL = 0x1C
READ_CALIBRATION_OPERATOR_NAME = 0x1D
WRITE_CALIBRATION_OPERATOR_NAME = 0x1E
GET_SER_NO = 0x1F
SET_SER_NO = 0x20
READ_CALIBRATION_DATE = 0x21
WRITE_CALIBRATION_DATE = 0x22

# Acquisition and mode control
STOP_TRANSMISSION = 0x23
START_TRANSMISSION = 0x24
CLEAR_BUFFER_ABORT_TX = 0x25
GET_MODE = 0x26
SET_MODE = 0x27
GET_SOFTWARE_CONFIGURATION = 0x2A
FIRMWARE_VERSION = 0x2B

# Protection, ranges, and raw values
GET_PROHIBIT_SET_ZERO = 0x32
WRITE_PROHIBIT_SET_ZERO = 0x33
WRITE_INPUT_RANGE = 0x34
SET_INJECT_VAL_OR_OFFSET = 0x35
GET_HARDWARE_VERSION = 0x36
GET_CUSTOM_SER_NO = 0x37
SET_CUSTOM_SER_NO = 0x38
GET_MANUFACTURER_SER_NO = 0x39
GET_RAW_VALUE = 0x3A
GET_VALUE = 0x3B
CLEAR_MAX_VALUE = 0x3C
GET_LAST_PROTOCOL_ERROR = 0x42
GET_LAST_VALUE_ERROR = 0x43
ERASE_ERROR_MEMORY = 0x44
GET_SENSOR_PLUGGED = 0x45

# FT sensor, TX mapping, and digital filters
READ_FT_SENSOR_CAL = 0x47
WRITE_FT_SENSOR_CAL = 0x48
GET_TX_MAPPING = 0x49
SET_TX_MAPPING = 0x4A
GET_DIGI_FILT_TYPE = 0x4B
SET_DIGI_FILT_TYPE = 0x4C
READ_DIGI_FILT_CUT_OFF = 0x4D
WRITE_DIGI_FILT_CUT_OFF = 0x4E
READ_DIGI_FILT_COEFF = 0x4F
WRITE_DIGI_FILT_COEFF = 0x50
GET_DIGI_FILT_ON_OFF = 0x51
SET_DIGI_FILT_ON_OFF = 0x52
READ_MAX_MIN_VAL = 0x53
GET_FT_SENSOR_CAL_ARR_NO = 0x54
SET_FT_SENSOR_CAL_ARR_NO = 0x55

# Device hours, password, and digital I/O
READ_DEVICE_HOURS = 0x56
WRITE_DEVICE_HOURS = 0x57
SET_PASSWORD = 0x58
GET_DIO_DIRECTION = 0x59
SET_DIO_DIRECTION = 0x5A
GET_DIO_TYPE = 0x5B
SET_DIO_TYPE = 0x5C
GET_DIO_LEVEL = 0x5D
SET_DIO_LEVEL = 0x5E
READ_DIO_THRESHOLD = 0x5F
WRITE_DIO_THRESHOLD = 0x60
GET_DIO_INITIAL_LEVEL = 0x61
SET_DIO_INITIAL_LEVEL = 0x62
READ_DATA_RATE_RANGE = 0x63

# TEDS, counter/frequency, logger, and filesystem
READ_TEDS_DATA_ENTRY = 0x64
READ_TEDS_RAW_ARRAY = 0x65
WRITE_TEDS_BYTES = 0x66
STORE_TEDS_DATA = 0x67
GET_TEDS_ACTIVE = 0x68
READ_COUNTER_FREQ_MODE = 0x69
WRITE_COUNTER_FREQ_MODE = 0x6A
READ_CLOCK_TIME = 0x6B
WRITE_CLOCK_TIME = 0x6C
READ_LOGGER_SETTINGS = 0x6D
WRITE_LOGGER_SETTINGS = 0x6E
CONTROL_LOGGER = 0x6F
QUERY_FILE_SYSTEM = 0x70
OPEN_FILE_DIR = 0x71
GET_FILE_INFO = 0x72
READ_FILE = 0x73
READ_FILE_EXTENDED = 0x74
READ_VALUE_STRING = 0x75

# Special mode and interface settings
PREPARE_SPECIAL_MODE = 0x77
RESET_DEVICE = 0x78
RELEASE_INTERFACE = 0x7A
READ_INTERFACE_SETTING = 0x7B
WRITE_INTERFACE_SETTING = 0x7C
PREP_READ_FT_SENSOR = 0x7D
STORE_DIGI_FILT = 0x7E
STORE_FT_SENSOR_CAL = 0x7F
GET_TX_MODE = 0x80
SET_TX_MODE = 0x81

# Timing, CAN, analog filter, and blocking
READ_DEBOUNCE_TIME = 0x86
WRITE_DEBOUNCE_TIME = 0x87
READ_DATA_RATE = 0x8A
WRITE_DATA_RATE = 0x8B
GET_CAN_SETTING = 0x8C
SET_CAN_SETTING = 0x8D
READ_ANALOG_FILTER = 0x90
WRITE_ANALOG_FILTER = 0x91
SWITCH_BLOCKING = 0x92
GET_COMMAND_AVAILABLE = 0x93

# Auto-zero, offsets, and linearization
READ_NOISE_CUT_THRESHOLD = 0x94
WRITE_NOISE_CUT_THRESHOLD = 0x95
READ_AUTO_ZERO_SETTING = 0x96
WRITE_AUTO_ZERO_SETTING = 0x97
GET_AUTO_ZERO_PROPERTY = 0x98
SET_AUTO_ZERO_PROPERTY = 0x99
READ_USER_OFFSET = 0x9A
WRITE_USER_OFFSET = 0x9B
READ_LINEARIZATION_VALUE = 0x9C
WRITE_LINEARIZATION_VALUE = 0x9D
STORE_LINEARIZATION = 0x9E
GET_INPUT_TYPE = 0xA2
SET_INPUT_TYPE = 0xA3
