"""Interface-related constants for Read/WriteInterfaceSetting.

Source: official GSV protocol specification.
"""

# Basic settings: physical interface type
RS232 = 1
UART_3V3 = 2
USB = 3
CAN = 4
ETHERNET_100BASE_TX = 5
RS422 = 6
SPI_MASTER = 7

# Basic settings: application layer type
GSV_PROTOCOL = 1
CANOPEN = 2
ETHERCAT_COE = 3
MONITOR_TEXT = 4
SCALED_SINT16 = 5

# Basic settings flags: bit positions
FLAG_RX_READY_BIT = 0
FLAG_TX_READY_BIT = 1
FLAG_WRITE_ACCESS_BIT = 2
FLAG_INTEGER_BINARY_OFFSET_BIT = 3
FLAG_PERMANENT_TX_RAM_BIT = 4
FLAG_PERMANENT_TX_EEPROM_BIT = 5
FLAG_SWITCHABLE_BIT = 16
FLAG_USES_SERVICE_OR_DEVICE_ADDRESS_BIT = 17
FLAG_ADDRESS_CHANGEABLE_BIT = 18
FLAG_MEASUREMENT_CRC_ENABLED_BIT = 19

# Basic settings flags: masks
FLAG_RX_READY = 1 << FLAG_RX_READY_BIT
FLAG_TX_READY = 1 << FLAG_TX_READY_BIT
FLAG_WRITE_ACCESS = 1 << FLAG_WRITE_ACCESS_BIT
FLAG_INTEGER_BINARY_OFFSET = 1 << FLAG_INTEGER_BINARY_OFFSET_BIT
FLAG_PERMANENT_TX_RAM = 1 << FLAG_PERMANENT_TX_RAM_BIT
FLAG_PERMANENT_TX_EEPROM = 1 << FLAG_PERMANENT_TX_EEPROM_BIT
FLAG_SWITCHABLE = 1 << FLAG_SWITCHABLE_BIT
FLAG_USES_SERVICE_OR_DEVICE_ADDRESS = 1 << FLAG_USES_SERVICE_OR_DEVICE_ADDRESS_BIT
FLAG_ADDRESS_CHANGEABLE = 1 << FLAG_ADDRESS_CHANGEABLE_BIT
FLAG_MEASUREMENT_CRC_ENABLED = 1 << FLAG_MEASUREMENT_CRC_ENABLED_BIT

# Extended settings: type enum
SET_MASK_ALLOWED_BITS = 1
CLEAR_MASK_ALLOWED_BITS = 2
MUTUALLY_EXCLUSIVE_INTERFACES = 3
ACTIVE_BAUDRATE = 4
AVAILABLE_BAUDRATE = 5
ACTIVE_SERVICE_ID_COUNT = 6
CAN_COMMAND_ID_HOST_TO_DEVICE = 7
CAN_COMMAND_RESPONSE_ID_DEVICE_TO_HOST = 8
CAN_MEASUREMENT_FRAME_ID_DEVICE_TO_HOST = 9
CAN_MULTICAST_ID_HOST_TO_DEVICES = 10
CANOPEN_NODE_ID = 11
DEVICE_STATE = 16
CANOPEN_TRANSMISSION_TYPE_AND_EVENT_TIMER = 17
CANOPEN_INHIBIT_TIME_AND_HEARTBEAT_TIMER = 18
ACTIVE_CHANNEL_COUNT = 19
INTEGER_MEASUREMENT_SCALE_FACTOR = 20

# Device state values
STATE_OFF = 0
STATE_INIT_OR_STOPPED = 2
STATE_PRE_OPERATIONAL = 4
STATE_SAFE_OPERATIONAL = 8
STATE_OPERATIONAL = 12
